### ISSUE TITLE
password incorrect?

### ISSUE THREAD

**Issue by 0x1f415** [WMCAlliance/BukkitIRCd#111]
disclosure: I'm pretty new to IRC so forgive me if this is a newbie question.

running cauldron 1.7.10-1.1286.06.216, latest BukkitIRCd.
deleted and recreated all relevant config files, then edited:

```
oper-password: foo
oper-username: bar
```

reloaded config in the server console (open over ssh), opened my weechat and typed in the server buffer `/oper foo bar`, sever replied `Password Incorrect`.

what am I doing wrong?

**Comment by WizardCM** [comment]
I'm assuming you're using the Standalone/built in IRC server, is your IRC username/nickname identical to oper-username? I haven't used the Standalone server enough to know it back-to-front yet.

Truthfully, we should really have a file that allows you to specify the nicknames and idents of all IRC Ops, rather than having a global oper-user and oper-pass. Thoughts, @Mu5tank05?

**Comment by 0x1f415** [comment]
the oper account doesn't have to be the same username as the IRC account user or nick - it seems I was just confusing the username and password fields :sweat_smile:. thanks for your help.

**Comment by WizardCM** [comment]
Ah yes, that would do it. xD Glad you got it sorted. :)
