### ISSUE TITLE
If kicked ingame, kick in IRC too, don't disconnect

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/BukkitIRCd#6]
If an ingame player kicks an ingame player, the IRC player disconnects with

WizardCM-mc has quit (Kicked: Message here)

Instead, actually kick the player from IRC at the same time.

**Comment by Haulien** [comment]
Best way I can think of this is to call the kick command prior to disconnecting the bot, as to avoid having a useless connection to the server.

**Comment by chyyran** [comment]
Working on this here f7c10d354b5f1e0c9f1ea56c4b9ec4ec6a7390b7

Got InspIRCd working for it, by the latest it should take me until the end of the week to get it working for standalone.

I had to use some workarounds for it though, since PlayerKickEvent doesn't give the kicker, I had it listen to kick commands listed under a config option. If the kicker has bukkitircd.kick, it'll send a KICK Rawsend command instead of a QUIT

**Comment by chyyran** [comment]
Fixed in pull request #26
